### ISSUE TITLE
"基于连通性状态压缩的动态规划问题"的压缩包下载后显示已损坏

### ISSUE THREAD

**Issue by memset0** [enkerewpo/OI-Public-Library#1]
2008国家集训队论文 Day2

**Comment by enkerewpo** [comment]
压缩包里是CDQ插头DP的课件。
这个课件我单独放在【学习资料】里有一份：[在这里](https://github.com/enkerewpo/OI-Public-Library/blob/master/%E5%9B%BD%E5%86%85%E5%AD%A6%E4%B9%A0%E8%B5%84%E6%96%99/%E5%9F%BA%E4%BA%8E%E8%BF%9E%E9%80%9A%E6%80%A7%E7%8A%B6%E6%80%81%E5%8E%8B%E7%BC%A9%E7%9A%84%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%92%E9%97%AE%E9%A2%98-Cdq.ppt)。

**Comment by memset0** [comment]
thanks!
