### ISSUE TITLE
哪里能找到IOI集训队论文？

### ISSUE THREAD

**Issue by nanmenyangde** [enkerewpo/OI-Public-Library#18]
rt

**Comment by enkerewpo** [comment]
目前的集训队论文都在这里：[IOI中国国家候选队论文](https://github.com/enkerewpo/OI-Public-Library/tree/master/IOI%E4%B8%AD%E5%9B%BD%E5%9B%BD%E5%AE%B6%E5%80%99%E9%80%89%E9%98%9F%E8%AE%BA%E6%96%87) 😀
