### ISSUE TITLE
求添加2018年的论文集

### ISSUE THREAD

**Issue by nosta-tianya** [enkerewpo/OI-Public-Library#3]
如题

**Comment by enkerewpo** [comment]
→→→[NOI2018集训队论文](https://github.com/enkerewpo/OI-Public-Library/blob/master/%E5%9B%BD%E5%AE%B6%E9%9B%86%E8%AE%AD%E9%98%9F%E8%AE%BA%E6%96%871999-2017/IOI2018%E4%B8%AD%E5%9B%BD%E5%9B%BD%E5%AE%B6%E5%80%99%E9%80%89%E9%98%9F%E8%AE%BA%E6%96%87%E9%9B%86%E6%AD%A3%E5%BC%8F%E7%89%88.pdf)←←←

**Comment by nosta-tianya** [comment]
thx

**Comment by enkerewpo** [comment]
~~~
